lib/blog_web/router.ex
defmodule BlogWeb.Router do
  use BlogWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", BlogWeb do
    pipe_through :browser

    get "/", PostController, :index
    get "/search", PostController, :search
    get "/rss", RSSController, :index
    get "/:slug", PostController, :show
  end

end

lib/blog/application.ex
defmodule Blog.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  def start(_type, _args) do
    # List all child processes to be supervised
    children = [
      { Blog.Posts.PostsManager, Blog.Posts.PostsManager.initialize() },
      {Phoenix.PubSub, name: Blog.PubSub},
      # Start the endpoint when the application starts
      BlogWeb.Endpoint
      # Starts a worker by calling: Blog.Worker.start_link(arg)
      # {Blog.Worker, arg},
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Blog.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    BlogWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/blog/posts/post.ex
defmodule Blog.Posts.Post do
  defstruct title: nil, date: nil, text: nil, intro: nil, slug: nil, tags: nil

  alias Blog.Services.MarkdownService

  def compile(file) do
    post = %Blog.Posts.Post{
      slug: file_to_slug(file)
    }

    Path.join(["#{:code.priv_dir(:blog)}/posts", file])
    |> File.read!
    |> split
    |> extract(post)
  end

  defp file_to_slug(file) do
    String.replace(file, ~r/\.md$/, "")
  end

  defp split(data) do
    [frontmatter, markdown] = String.split(data, ~r/\n-{3,}\n/, parts: 2)
    {parse_yaml(frontmatter), MarkdownService.parse_as_html(markdown)}
  end

  defp parse_yaml(yaml) do
    [parsed] = :yamerl_constr.string(yaml)
    parsed
  end

  defp extract_intro(content) do
    content
    |> HtmlSanitizeEx.strip_tags()
    |> String.slice(0..300)
  end

  defp extract({props, content}, post) do
    %Blog.Posts.Post{post |
      title: get_prop(props, "title"),
      date: Timex.parse!(get_prop(props, "date"), "{ISO:Extended}"),
      intro: extract_intro(content),
      tags: String.split(get_prop(props, "tags"), ","),
      text: content}
  end

  defp get_prop(props, key) do
    case :proplists.get_value(String.to_charlist(key), props) do
      :undefined -> nil
      x -> to_string(x)
    end
  end
end

lib/blog/posts/posts_manager.ex
defmodule Blog.Posts.PostsManager do
  use Agent
  alias Blog.Posts.Post

  def start_link(initial_value) do
    Agent.start_link(fn -> initial_value end, name: __MODULE__)
  end

  def initialize(), do: get_posts()

  def sort_post_by_date(postA, postB) do
    Timex.diff(postA.date, postB.date) > 0
  end

  defp get_posts do
    File.ls!("#{:code.priv_dir(:blog)}/posts")
    |> Enum.map(&Post.compile/1)
    |> Enum.sort(&sort_post_by_date/2)
  end

  def all_posts do
    Agent.get(__MODULE__, &(&1))
  end

  def get_by_tags(tags) do
    posts = all_posts()

    posts_tagged = Enum.filter(posts, fn post ->
      Enum.find(post.tags, &(Enum.member?(tags, &1)))
    end)

    case posts_tagged do
      [] -> {:not_found, nil}
      post -> {:ok, post}
    end
  end

  def get_by_slug(slug) do
    posts = all_posts()

    case Enum.find(posts, &(&1.slug == slug)) do
      nil -> {:not_found, nil}
      post -> {:ok, post}
    end
  end
end

lib/blog/services/markdown_service.ex
defmodule Blog.Services.MarkdownService do
  def parse_as_html(markdown) do
    Earmark.as_html!(markdown, %Earmark.Options{code_class_prefix: "language- lang-"})
  end
end

lib/blog_web/controllers/page_controller.ex
defmodule BlogWeb.PageController do
  use BlogWeb, :controller

  def about(conn, _params) do
    render conn, "about.html"
  end
end

lib/blog_web/controllers/post_controller.ex
defmodule BlogWeb.PostController do
  use BlogWeb, :controller
  alias Blog.Posts.PostsManager

  def index(conn, _params) do
    render conn, "index.html", posts: PostsManager.all_posts
  end

  def show(conn, %{"slug" => slug}) do
    case PostsManager.get_by_slug(slug) do
      {:ok, post} -> render conn, "show.html", post: post
      {:not_found, nil} -> not_found(conn)
    end
  end

  def search(conn, %{"tag" => tag}) do
    case PostsManager.get_by_tags([tag]) do
      {:ok, posts} -> render conn, "index.html", posts: posts
      {:not_found, nil} -> not_found(conn)
    end
  end

  def not_found(conn) do
    conn
    |> put_status(:not_found)
    |> render(BlogWeb.ErrorView, "404.html")
  end
end

lib/blog_web/controllers/rss_controller.ex
defmodule BlogWeb.RSSController do
  use BlogWeb, :controller

  def index(conn, _params) do
    redirect(conn, external: "http://fetchrss.com/rss/6474617bafe4ff34332982826474fd06677a46535867c392.xml")
  end
end

lib/blog_web/views/error_view.ex
defmodule BlogWeb.ErrorView do
  use BlogWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end

  def title(_html, _assigns), do: "404 - Page not found"
end

lib/blog_web/views/layout_view.ex
defmodule BlogWeb.LayoutView do
  use BlogWeb, :view

  # Phoenix LiveDashboard is available only in development by default,
  # so we instruct Elixir to not warn if the dashboard route is missing.
  @compile {:no_warn_undefined, {Routes, :live_dashboard_path, 2}}

  def title(assigns) do
    module = Phoenix.Controller.view_module(assigns.conn)
    template = Phoenix.Controller.view_template(assigns.conn)
    module.title(template, assigns)
  end
end

lib/blog_web/views/post_view.ex
defmodule BlogWeb.PostView do
  use BlogWeb, :view

  def relative_date(date) do
    Timex.Format.DateTime.Formatters.Relative.lformat!(date, "{relative}", "Brazil/East")
  end

  def title("index.html", _assigns), do: "Rafael Gonzaga - Home"
  def title("show.html", %{ post: post }), do: post.title
end

lib/blog_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title><%= title(assigns) %></title>
    <link rel="alternate" type="application/rss+xml" title="RafaelGSS Blog" href="/rss">
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-156375977-1"></script>
    <meta name="aplication-name" content="Rafael Gonzaga Blog">
    <meta name="description" content="A tech blog focused on Application Performance and Software Architecture. The Front-end is just JSON over here.">
    <meta name="keywords" content="microsservices,microsservicos,javascript,nodejs,performance,profiling,ddd,architecture,tech">
    <meta name="author" content="Rafael Gonzaga">
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-156375977-1');
    </script>
  </head>
  <body>
    <div id="app">
      <header>
        <h1>
          @rafaelgss tech blog
        </h1>
        <hr>
        <ul>
          <li>
            <a target="_blank" href="https://rafaelgss.github.io/portfolio/">Contact</a>
          </li>
          <li>
            <a href="<%= Routes.post_path @conn, :index %>">Publications</a>
          </li>
        </ul>
      </header>
      <main>
        <%= @inner_content %>
      </main>
      <footer>
        <span>© Rafael Gonzaga, Brasil - SP</span>
      </footer>
    </div>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/blog_web/templates/layout/app.html.heex
<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title><%= title(assigns) %></title>
    <link rel="alternate" type="application/rss+xml" title="RafaelGSS Blog" href="/rss">
    <link rel="stylesheet" href={Routes.static_path(@conn, "/assets/app.css")}/>
    <link rel="stylesheet" href={Routes.static_path(@conn, "/assets/prism.css")}/>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-156375977-1"></script>
    <meta name="aplication-name" content="Rafael Gonzaga Blog">
    <meta name="description" content="Tech insights on Performance, Security and Node.js from Rafael Gonzaga, Node.js TSC member">
    <meta name="keywords" content="microsservices,microsservicos,javascript,nodejs,performance,profiling,ddd,architecture,tech">
    <meta name="author" content="Rafael Gonzaga">
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-156375977-1');
    </script>
  </head>
  <body>
    <div id="app">
      <header>
        <h1>
          @rafaelgss tech blog
        </h1>
        <ul>
          <li>
            <a target="_blank" href="https://rafaelgss.dev">Contact</a>
          </li>
          <li>
            <a href={Routes.post_path @conn, :index}>Publications</a>
          </li>
        </ul>
      </header>
      <main>
        <%= @inner_content %>
      </main>
      <footer>
        <span>© Rafael Gonzaga, Brasil - SP</span>
      </footer>
    </div>
    <script type="text/javascript" src={Routes.static_path(@conn, "/assets/app.js")}></script>
    <script type="text/javascript" src={Routes.static_path(@conn, "/assets/prism.js")}></script>
  </body>
</html>

lib/blog_web/templates/layout/live.html.heex
<main class="container">
  <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>

lib/blog_web/templates/post/index.html.eex
<%= for post <- @posts do %>
<section>
  <div class="teaser">
    <h2>
      <a href="<%= Routes.post_path @conn, :show, post.slug %>"> <%= post.title %>
      </a>
    </h2>
    <div class="posts__extra">
      <span class="posts__date"><%= relative_date(post.date) %></span>
      <div class="posts__tags">
        <%= for tag <- post.tags do %>
          <a href="
            <%= Routes.post_path @conn, :search, tag: tag %>
            " class="posts__tag"><%= tag %></a>
        <% end %>
      </div>
    </div>

    <p>
      <%= post.intro %>...
      <a class="more" href="<%= Routes.post_path @conn, :show, post.slug %>">
        read more
      </a>
    </p>
  </div>
</section>
<% end %>

lib/blog_web/templates/post/index.html.heex
<%= for post <- @posts do %>
<section>
  <div class="teaser">
    <h2>
      <a href={Routes.post_path @conn, :show, post.slug}> <%= post.title %>
      </a>
    </h2>
    <div class="posts__extra">
      <span class="posts__date"><%= relative_date(post.date) %></span>
      <div class="posts__tags">
        <%= for tag <- post.tags do %>
          <a href={Routes.post_path @conn, :search, tag: tag} class="posts__tag"><%= tag %></a>
        <% end %>
      </div>
    </div>

    <p>
      <%= post.intro %>...
      <a class="more" href={Routes.post_path @conn, :show, post.slug}>
        read more
      </a>
    </p>
  </div>
</section>
<% end %>

lib/blog_web/templates/post/show.html.eex
<script type="application/ld+json">
  {
      "@context" : "http://schema.org",
      "@type" : "Article",
      "name" : "<%= @post.title %>",
      "author" : {
        "@type" : "Person",
        "name" : "Rafael Gonzaga"
      },
      "sameAs" : [
        "https://twitter.com/_rafaelgss",
        "https://github.com/rafaelgss",
        "https://linkedin.com/in/rafaelgss"
      ]
    }
</script>
<section class="post__raw-data">
  <%= raw(@post.text) %>
  <hr style="margin-top: 3em;"/>
</section>
<section class="post_comments">
  <script src="https://utteranc.es/client.js"
          repo="rafaelgss/blog"
          issue-term="<%= @post.title %>"
          label="comment"
          theme="github-light"
          crossorigin="anonymous"
          async>
  </script>
</section>

lib/blog_web/templates/post/show.html.heex
<script type="application/ld+json">
  {
      "@context" : "http://schema.org",
      "@type" : "Article",
      "name" : "<%= @post.title %>",
      "author" : {
        "@type" : "Person",
        "name" : "Rafael Gonzaga"
      },
      "sameAs" : [
        "https://twitter.com/_rafaelgss",
        "https://github.com/rafaelgss",
        "https://linkedin.com/in/rafaelgss"
      ]
    }
</script>
<section class="post__raw-data">
  <%= raw(@post.text) %>
  <hr style="margin-top: 3em;"/>
</section>
<section class="post_comments">
  <script src="https://utteranc.es/client.js"
          repo="rafaelgss/blog"
          issue-term={@post.title}
          label="comment"
          theme="github-light"
          crossorigin="anonymous"
          async>
  </script>
</section>